apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include "getConfigFiles" . | sha256sum }}
spec:
  replicas: {{ .Values.deployment.replicasCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm.name" . }}
      app.kubernetes.io/instance: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helm.name" . }}
        app.kubernetes.io/instance: {{ .Chart.Name }}
      annotations:
        checksum/config: {{ include "getConfigFiles" . | sha256sum }}
        {{- if .Values.deployment.annotations }}
          {{- toYaml .Values.deployment.annotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-serviceaccount
    {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image }}"
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: {{ .Chart.Name }}-certs
              mountPath: /app/certs
              readOnly: true
            - name: {{ .Chart.Name }}-alert-templates
              mountPath: "/app/config/templates"
              readOnly: true
            - name: {{ .Chart.Name }}-alertconfig
              mountPath: "/app/config"
              readOnly: true
            - name: {{ .Chart.Name }}-config
              mountPath: /app/connaisseur-config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: {{ .Chart.Name }}-config-secrets
              mountPath: /app/connaisseur-config/config-secrets.yaml
              subPath: config-secrets.yaml
              readOnly: true
            - name: {{ .Chart.Name }}-config-sigstore
              mountPath: /app/.sigstore
              readOnly: false
            {{ include "external-secrets-mount" . | nindent 12}}
            {{ include "cosignCertVolMount" . | nindent 12 }}
            {{- if .Values.deployment.extraVolumeMounts }}
            {{ tpl (toYaml .Values.deployment.extraVolumeMounts) . | nindent 12}}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-env
            - secretRef:
                name: {{ .Chart.Name }}-env-secrets
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
        {{- if .Values.deployment.extraContainers }}
        {{ tpl (toYaml .Values.deployment.extraContainers) . | nindent 8}}
        {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ .Chart.Name }}-certs
          secret:
            secretName: {{ .Chart.Name }}-tls
        - name: {{ .Chart.Name }}-alertconfig
          secret:
            secretName: {{ .Chart.Name }}-alertconfig
        - name: {{ .Chart.Name }}-alert-templates
          configMap:
            name: {{ .Chart.Name }}-alert-templates
        - name: {{ .Chart.Name }}-config
          configMap:
            name: {{ .Chart.Name }}-config
        - name: {{ .Chart.Name }}-config-secrets
          secret:
            secretName: {{ .Chart.Name }}-config-secrets
        - name: {{ .Chart.Name }}-config-sigstore
          emptyDir: {}
        {{ include "external-secrets-vol" . | nindent 8}}
        {{ include "cosignCertVol" . | nindent 8 }}
        {{- if .Values.deployment.extraVolumes }}
        {{ tpl (toYaml .Values.deployment.extraVolumes) . | nindent 8}}
        {{- end }}
