apiVersion: v2
name: connaisseur
description: Helm chart for Connaisseur - a Kubernetes admission controller to integrate container image signature verification and trust pinning into a cluster.
type: application
version: 2.9.1
appVersion: 3.9.1
keywords:
  - container image
  - signature
  - verification
home: https://sse-secure-systems.github.io/connaisseur/latest
sources:
  - https://github.com/sse-secure-systems/connaisseur
icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
maintainers:
  - name: Philipp Belitz
    email: pbe@systemsecurity.com
  - name: Teetje Stark
    email: tst@systemsecurity.com
  - name: Anneke Breust
    email: abr@systemsecurity.com
  - name: Christopher Filsinger
    email: cfi@systemsecurity.com
