apiVersion: v1
entries:
  connaisseur:
  - apiVersion: v2
    appVersion: 2.7.0
    created: "2022-12-23T13:16:39.494796209Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 7974ecacdd4dfacde94bd5be1f1fc301eff3f97919a526bc62c9c1659b3f17f9
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.5.0.tgz
    version: 1.5.0
  - apiVersion: v2
    appVersion: 2.6.4
    created: "2022-12-23T13:16:39.493776383Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 360a9134f3bf8e88f0cf5e67a4a90f4c9354e9c7e9a714ed503927461c1ba5a6
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.4.4.tgz
    version: 1.4.4
  - apiVersion: v2
    appVersion: 2.6.3
    created: "2022-12-23T13:16:39.492760357Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: c1c66f0f668ed4dc5abf872d132c4cba6666955a588401e9207fcbc0487d4387
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.4.3.tgz
    version: 1.4.3
  - apiVersion: v2
    appVersion: 2.6.2
    created: "2022-12-23T13:16:39.491778232Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 4d6ffb33ef95d3ea0b370348da63671c29297d7f65c309df9f4196e44b141ea1
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.4.2.tgz
    version: 1.4.2
  - apiVersion: v2
    appVersion: 2.6.1
    created: "2022-12-23T13:16:39.490568401Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 67409d5c1a614171b4492bae2deb1a9d2e283daacb645c113f51ffea1a537760
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.4.1.tgz
    version: 1.4.1
  - apiVersion: v2
    appVersion: 2.6.0
    created: "2022-12-23T13:16:39.489472673Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 19701a66fd9d1c665cb2fd0d28e7bfb674ac421fb9c2e10bf4610b8998b47523
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.4.0.tgz
    version: 1.4.0
  - apiVersion: v2
    appVersion: 2.5.3
    created: "2022-12-23T13:16:39.488471447Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 58be2dbc52e7e37334afe70dae72dee80ea1cdef1079292b53869e68ffe604ba
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.3.3.tgz
    version: 1.3.3
  - apiVersion: v2
    appVersion: 2.5.2
    created: "2022-12-23T13:16:39.487507123Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: fe7eaf75a7c467330bed7d9f02a6cb74eb19aa6a7c6db9e855d2229a96e107f5
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.3.2.tgz
    version: 1.3.2
  - apiVersion: v2
    appVersion: 2.5.1
    created: "2022-12-23T13:16:39.486281191Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 485ec3bb56e28ca92d479dd70f58302c099e879d52117c4e88fe01e6af880722
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.3.1.tgz
    version: 1.3.1
  - apiVersion: v2
    appVersion: 2.5.0
    created: "2022-12-23T13:16:39.484542047Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 2f9c1c618ac4ad9036b6697a5af8fa7c405b8f8ac87bd99228b2a6cb6db2e7c3
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    appVersion: 2.4.1
    created: "2022-12-23T13:16:39.482425893Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 0e43fc30de3927c62f10a66a5fb828f5209452b5a5496651788746ac975daa7b
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v2
    appVersion: 2.4.0
    created: "2022-12-23T13:16:39.481450768Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 0727c9dcfe25813dcbf690fee8d849d16d7fd7d053a0e683f956a8770b4c1d9f
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 2.3.0
    created: "2022-12-23T13:16:39.480493243Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 3fe6474b7c384c99ac5420932dc980c6d20f7887ce5903168162ddecaba5c7dd
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 2.2.1
    created: "2022-12-23T13:16:39.47958932Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 9571292a2478241008fa3e22e95bc65b36bc1313d623a3537ce496c72edd4fa3
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 2.2.0
    created: "2022-12-23T13:16:39.478639196Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 1e3f943e5569957d2c60d99f770c206cfe6297dd1f04c248f500c8156a9b2d23
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.0.0.tgz
    version: 1.0.0
generated: "2022-12-23T13:16:39.477448565Z"
