apiVersion: v2
name: connaisseur
description: A Helm chart for the Connaisseur Admission Controller to validate docker image signatures.
type: application
version: 1.0.0
appVersion: 2.0.0
keywords:
  - docker image
  - signature
  - verification
home: https://github.com/sse-secure-systems/connaisseur
sources:
  - https://github.com/sse-secure-systems/connaisseur
maintainers:
  - name: Philipp Belitz
    email: philipp.belitz@securesystems.de
  - name: Peter Thomassen
    email: peter.thomassen@securesystems.de
  - name: Christoph Hamsen
    email: christoph.hamsen@securesystems.de
