name: unit-test

permissions: {}

on:
  workflow_call:
    inputs:
      jobs_to_run:
        description: "Which unit tests should be run: 'all', 'only-required', 'skip-all'?"
        type: string
        default: "all"

jobs:
  gotest:
    name: unit tests
    runs-on: ubuntu-latest
    if: inputs.jobs_to_run != 'skip-all'
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.22'
      - name: Test
        run: go test ./internal/... -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
