name: cleanup registry

on:
  workflow_call:

permissions: {}

jobs:
  cleanup-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup test images in 'connaisseur-test'
        uses: snok/container-retention-policy@3b0972b2276b171b212f8c4efbca59ebba26eceb # v3.0.1
        with:
          image-names: connaisseur-test
          cut-off: 3w
          timestamp-to-use: updated_at
          account: sse-secure-systems
          token: ${{ secrets.GHCR_PAT }}
      - name: Cleanup dangling images without tag
        uses: snok/container-retention-policy@3b0972b2276b171b212f8c4efbca59ebba26eceb # v3.0.1
        with:
          image-names: connaisseur*
          tag-selection: untagged
          cut-off: 4h
          timestamp-to-use: updated_at
          account: sse-secure-systems
          token: ${{ secrets.GHCR_PAT }}
      - name: Cleanup all connaisseur images
        uses: snok/container-retention-policy@3b0972b2276b171b212f8c4efbca59ebba26eceb # v3.0.1
        with:
          image-names: connaisseur
          image-tags: "!master !develop !v*"
          cut-off: 4d
          timestamp-to-use: updated_at
          account: sse-secure-systems
          token: ${{ secrets.GHCR_PAT }}
